# Bamboo Sushi LoHi Scraping Configuration
# Website: https://bamboosushi.com/location/lohi
# Happy Hour: Monday-Friday 4-6pm, Saturday-Sunday 12-4pm

name: "Bamboo Sushi"
slug: "bamboo-sushi"

scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Focus on main content areas
  content_containers:
    - ".happy-hour-content"
    - ".location-content"
    - ".main-content"
    - "main"
    - ".page-content" 
    - "article"
    - ".content"
  
  # Custom CSS selectors for specific content
  custom_selectors:
    happy_hour_times: ".hours, .time, .schedule, .happy-hour"
    deal_description: "h1, h2, h3, h4, p, li, .description"
    pricing: ".price, .cost, span"
  
  # Regex patterns for extracting structured data - focus only on happy hour times (4-6pm and 12-4pm)
  time_pattern_regex: '(4|12)\s*(?::\d{2})?\s*(?:(pm|PM))?\s*[–-]\s*(6|4)\s*(?::\d{2})?\s*(pm|PM)'
  day_pattern_regex: '(Monday\s*-\s*Friday|Saturday\s*-\s*Sunday)(?=.*[Hh]appy)'
  price_pattern_regex: '\$(\d+(?:\.\d{2})?)'
  
  # Patterns to exclude from parsing to avoid noise
  exclude_patterns:
    - 'copyright'
    - 'privacy policy'
    - 'terms of service'
    - 'footer'
    - 'navigation'
    - 'header'
    - 'social media'
    - 'follow us'
    - 'newsletter'
    - 'careers'
    - 'gift cards'
    - 'Make a reservation'
    - 'Order Pickup'
    - 'delivery'
    
  # Content enhancement settings
  clean_whitespace: true
  remove_empty_lines: true
  min_description_length: 10
  max_description_length: 200

# Expected results based on website content:
# Monday-Friday: 4:00pm - 6:00pm
# Saturday-Sunday: 12:00pm - 4:00pm