restaurant_name: "Bezel Bar"
scraper_type: "config_based"
enabled: true
urls:
  - "https://www.bezeldenver.com/our-menus"

scraping_patterns:
  deal_patterns:
    # Happy hour timing
    - pattern: "(?i)every\\s+tuesday\\s*-\\s*friday[,\\s]+(\\d{1,2})\\s*-\\s*(\\d{1,2})\\s*pm"
      groups: [start_time, end_time]
      confidence: 0.9
      deal_type: "happy_hour"
      title: "Happy Hour"
      days_of_week: ["tuesday", "wednesday", "thursday", "friday"]
      
    # Pricing patterns
    - pattern: "draft\\s+beer[:\\s]*\\$(\\d+)"
      groups: [price]
      confidence: 0.9
      deal_type: "happy_hour"
      title: "Draft Beer Special"
      
    - pattern: "selected\\s+wines.*\\$(\\d+)\\s*-\\s*\\$(\\d+)"
      groups: [min_price, max_price]
      confidence: 0.9
      deal_type: "happy_hour"
      title: "Wine Specials"
      
    # Food specials with pricing
    - pattern: "([A-Z][a-z\\s]+):\\s*\\$(\\d+)\\s*\\(reduced\\s+from\\s*\\$(\\d+)\\)"
      groups: [item_name, sale_price, regular_price]
      confidence: 0.9
      deal_type: "happy_hour"
      
    # Specific food items
    - pattern: "(?i)(bezel\\s+board|bone\\s+marrow|french\\s+onion\\s+dip|blistered\\s+shishito|wagyu\\s+sliders)[:\\s]*\\$(\\d+)"
      groups: [item_name, price]
      confidence: 0.8
      deal_type: "happy_hour"

post_processing:
  deal_consolidation:
    - title: "Bezel Happy Hour"
      description: "Tuesday-Friday 4-6pm with $7 drafts, selected wines, and discounted bites"
      combine_similar: true
  
  price_formatting:
    currency_symbol: "$"
    format: "individual_prices"

confidence_threshold: 0.7
retry_attempts: 3
delay_between_requests: 1