# Custom scraping configuration for Blue Sushi Sake Grill LoDo
restaurant_name: "Blue Sushi Sake Grill"

# Main scraping configuration that the system expects
scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Custom selectors to target happy hour content specifically
  custom_selectors:
    happy_hour_content: ".content-section, .hours-section, [class*='happy'], [class*='hours']"
  
  # Enhanced regex patterns for Blue Sushi happy hour detection
  time_pattern_regex: '(\d{1,2})\s*(?::\d{2})?\s*(am|pm|AM|PM)?\s*-\s*(\d{1,2})\s*(?::\d{2})?\s*(pm|am|PM|AM)'
  day_pattern_regex: "(Monday-Saturday|Mon-Sat|Sunday|monday|tuesday|wednesday|thursday|friday|saturday|sunday|all day)"
  
  # Temporarily disable exclusions to see all available content
  exclude_patterns: []
    # - "Monday-Thursday: 11am-10pm"
    # - "Friday: 11am-10:30pm"  
    # - "Saturday: 12pm-10:30pm"  
    # - "Sunday: 12pm-9pm"
  
  # Target content containers for happy hour info - try multiple approaches
  content_containers:
    - ".happy-hour-section"
    - ".specials-section" 
    - ".hours-section"
    - "[class*='happy']"
    - ".location-details"
    - "main"