# Custom scraping configuration for Fogo de Chão
restaurant_name: "Fogo de Chão"

# Main scraping configuration that the system expects
scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Custom selectors to target specific happy hour content
  custom_selectors:
    happy_hour_content: "[class*='happy'], [class*='bar'], .content-section, .specials"
  
  # Enhanced regex patterns for Fogo de Chão specific happy hour patterns
  time_pattern_regex: "(?:Mon\\s*-\\s*Thu|Monday\\s*-\\s*Thursday)[:\\s]*(?:3:00\\s*PM|3\\s*PM)[\\s-]*(?:9:30\\s*PM|9:30PM)|(?:Fri|Friday)[:\\s]*(?:3:00\\s*PM|3\\s*PM)[\\s-]*(?:10:00\\s*PM|10PM)|(?:Sat|Saturday)[:\\s]*(?:2:00\\s*PM|2\\s*PM)[\\s-]*(?:10:00\\s*PM|10PM)|(?:Sun|Sunday)[:\\s]*(?:2:00\\s*PM|2\\s*PM)[\\s-]*(?:9:00\\s*PM|9PM)|(?:MON\\s*-\\s*FRI|Monday\\s*-\\s*Friday)[:\\s]*(?:11:30\\s*AM|11:30AM)[\\s-]*(?:3:00\\s*PM|3PM)"
  day_pattern_regex: "(?:Mon\\s*-\\s*Thu|Monday\\s*-\\s*Thursday|Fri|Friday|Sat|Saturday|Sun|Sunday|MON\\s*-\\s*FRI|Monday\\s*-\\s*Friday)"
  
  # Exclude generic mentions that aren't real deals
  exclude_patterns:
    - "all day happy hour"
    - "all-day happy hour"
    - "daily specials"
  
  # Target content containers for happy hour info
  content_containers:
    - ".content-section"
    - "[class*='happy']"
    - "[class*='bar']"
    - ".specials"