# Foraged Restaurant Scraping Configuration
# Website: https://www.foragedrestaurant.com/drink
# Happy hours: Sunday-Thursday 4-6 PM, Friday-Saturday 9:30-10:30 PM

name: "Foraged"
slug: "foraged"

scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Focus on areas containing hours and contact info
  content_containers:
    - "footer"
    - ".site-info" 
    - ".contact-info"
    - ".location-info"
    - "main"
    - "article"
    - ".content-wrapper"
  
  # Custom CSS selectors for specific content
  custom_selectors:
    happy_hour_times: ".hours, .time, .schedule, .special-hours"
    deal_description: "h1, h2, h3, h4, p, li, .description"
    pricing: ".price, .cost, span"
  
  # Regex patterns for extracting structured data - handle en-dash and implicit PM
  time_pattern_regex: '(\d{1,2})\s*(?::\d{2})?\s*(?:(am|pm|AM|PM))?\s*[–-]\s*(\d{1,2})\s*(?::\d{2})?\s*(?:(pm|am|PM|AM))?'
  day_pattern_regex: '(Sunday\s*-\s*Thursday|Friday\s*-\s*Saturday|sunday|monday|tuesday|wednesday|thursday|friday|saturday|late\s+night)'
  price_pattern_regex: '\$(\d+(?:\.\d{2})?)'
  
  # Patterns to exclude from parsing to avoid noise
  exclude_patterns:
    - 'copyright'
    - 'privacy policy'
    - 'terms of service'
    - 'footer'
    - 'navigation'
    - 'header'
    - 'social media'
    - 'follow us'
    - 'newsletter'
    - 'careers'
    - 'press'
    - 'omakase'
    - 'reservations'
    - 'private events'
    - 'catering'
    # Exclude operating hours and contact info
    - 'Location.*Denver, CO'
    - 'View Map'
    - 'Hours Monday Closed'
    - 'Tuesday - Thursday 4–9'
    - 'Friday - Saturday 4—10:30'
    - 'Sunday 4–9'
    - 'Contact info@'
    - '720-458-3837'
    - 'Social Press'
    
  # Content enhancement settings
  clean_whitespace: true
  remove_empty_lines: true
  min_description_length: 10
  max_description_length: 200

# Expected results based on website content:
# Sunday-Thursday: 4-6 PM (Happy Hour)
# Friday-Saturday: 9:30-10:30 PM (Late Night Happy Hour)