# Kumoya Denver Scraping Configuration  
# Website: https://www.kumoyadenver.com/happy-hour
# Happii Hour: Every day 5:00pm-6:00pm with specialty roll/skewer discounts

name: "Kumoya - Denver"
slug: "kumoya-denver"

scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Focus on main content areas
  content_containers:
    - ".happy-hour-content"
    - ".happii-hour-content"
    - ".specials-content"
    - ".main-content"
    - "main"
    - ".page-content" 
    - "article"
    - ".content"
  
  # Custom CSS selectors for specific content
  custom_selectors:
    happy_hour_times: ".hours, .time, .schedule, .happii-hour"
    deal_description: "h1, h2, h3, h4, p, li, .description"
    pricing: ".price, .cost, span"
  
  # Regex patterns for extracting structured data
  time_pattern_regex: '(\d{1,2})\s*(?::\d{2})?\s*(?:(am|pm|AM|PM))?\s*(?:to|[–-])\s*(\d{1,2})\s*(?::\d{2})?\s*(pm|am|PM|AM)'
  day_pattern_regex: '(Every\s+Day|Daily|every\s+day|daily)'
  price_pattern_regex: '\$(\d+(?:\.\d{2})?)'
  
  # Patterns to exclude from parsing to avoid noise
  exclude_patterns:
    - 'copyright'
    - 'privacy policy'
    - 'terms of service'
    - 'footer'
    - 'navigation'
    - 'header'
    - 'social media'
    - 'follow us'
    - 'newsletter'
    - 'careers'
    - 'gift cards'
    - 'group dining'
    - 'reservations'
    
  # Content enhancement settings
  clean_whitespace: true
  remove_empty_lines: true
  min_description_length: 10
  max_description_length: 200

# Expected results based on website content:
# Every Day: 5:00pm - 6:00pm
# 30% Off specialty rolls, 30% off skewers, 50% off tomadachi, drink specials