# Senor Bear Scraping Configuration
# Website: https://www.senorbeardenver.com/menus/#happy-hour
# Happy Hour: Menu available with cocktails, bocaditos, but no specific timing published

name: "Senor Bear"
slug: "senor-bear"

scraping_config:
  enabled: false  # Disabled since no timing info available on website
  fallback_to_static: true
  
  # Focus on main content areas
  content_containers:
    - ".happy-hour-content"
    - ".specials-content"
    - ".main-content"
    - "main"
    - ".page-content" 
    - "article"
    - ".content"
  
  # Custom CSS selectors for specific content
  custom_selectors:
    happy_hour_times: ".hours, .time, .schedule, .happy-hour"
    deal_description: "h1, h2, h3, h4, p, li, .description"
    pricing: ".price, .cost, span"
  
  # Basic patterns (would need timing info to be useful)
  time_pattern_regex: '(\d{1,2})\s*(?::\d{2})?\s*(?:(am|pm|AM|PM))?\s*[–-]\s*(\d{1,2})\s*(?::\d{2})?\s*(pm|am|PM|AM)'
  day_pattern_regex: '(Daily|Every\s+Day|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)'
  price_pattern_regex: '\$(\d+(?:\.\d{2})?)'
  
  # Patterns to exclude from parsing to avoid noise
  exclude_patterns:
    - 'copyright'
    - 'privacy policy'
    - 'terms of service'
    - 'footer'
    - 'navigation'
    - 'header'
    - 'social media'
    - 'follow us'
    - 'newsletter'
    - 'careers'
    - 'gift cards'
    - 'reservations'
    - 'contact'
    
  # Content enhancement settings
  clean_whitespace: true
  remove_empty_lines: true
  min_description_length: 10
  max_description_length: 200

# Expected results: No timing available on website, relies on static data