# STK Steakhouse Scraping Configuration
# Website: https://stksteakhouse.com/happenings/happy-hour/
# Note: Chain restaurant with generic happy hour page

name: "STK"
slug: "stk"

scraping_config:
  enabled: true
  fallback_to_static: true
  
  # Focus on main content areas
  content_containers:
    - ".happy-hour-content"
    - ".social-hour-content"
    - ".main-content"
    - "main"
    - ".page-content" 
    - "article"
    - ".content"
  
  # Custom CSS selectors for specific content
  custom_selectors:
    happy_hour_times: ".hours, .time, .schedule, .social-hours"
    deal_description: "h1, h2, h3, h4, p, li, .description"
    pricing: ".price, .cost, span"
  
  # Regex patterns for extracting structured data
  time_pattern_regex: '(\d{1,2})\s*(?::\d{2})?\s*(?:(am|pm|AM|PM))?\s*[–-]\s*(\d{1,2})\s*(?::\d{2})?\s*(?:(pm|am|PM|AM))?'
  day_pattern_regex: '(Monday\s*-\s*Friday|Tuesday\s*-\s*Saturday|Sunday\s*-\s*Thursday|Friday\s*-\s*Saturday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|weekday|weekend|daily)'
  price_pattern_regex: '\$(\d+(?:\.\d{2})?)'
  
  # Patterns to exclude from parsing to avoid noise
  exclude_patterns:
    - 'copyright'
    - 'privacy policy'
    - 'terms of service'
    - 'footer'
    - 'navigation'
    - 'header'
    - 'social media'
    - 'follow us'
    - 'newsletter'
    - 'careers'
    - 'gift cards'
    - 'private events'
    - 'catering'
    - 'meat market'
    - 'locations'
    
  # Content enhancement settings
  clean_whitespace: true
  remove_empty_lines: true
  min_description_length: 10
  max_description_length: 200

# Expected results: Chain restaurant may have limited specific timing
# May need to fall back to generic "$3 $6 $9 Happy Hour" information